runtime: nodejs18

env: standard
env_variables:
  REACT_APP_API_URL: "https://api.futurin.tw"

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
- url: /(.*\.(gif|png|jpg|css|js))$
  static_files: build/\1
  upload: build/(.*\.(gif|png|jpg|css|js))$
  secure: always
  redirect_http_response_code: 301

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
  redirect_http_response_code: 301
